dist: xenial
language: cpp

compiler:
  - gcc

addons:
  apt:
    packages:
    - libopencv-dev
    - libopencv-imgproc-dev
    - libopencv-photo-dev
    - libboost-filesystem-dev
    - libboost-serialization-dev
    - libboost-locale-dev
    - libxml2-dev
    - libfreetype6-dev
    - libpng-dev
    - libjpeg-dev
    - libtiff-dev
    - libopenexr-dev
    - libpython3-dev
    - ruby-dev
    - swig

before_script:
  # create a build folder for the out-of-source build
  - mkdir build
  # switch to build directory
  - cd build
  # run cmake; here we assume that the project's
  # top-level CMakeLists.txt is located at '..'
  - cmake ..

script:
  # once CMake has done its job we just build using make as usual
  - make
