dist: xenial
language: cpp

compiler:
  - gcc

addons:
    apt:
      update: false
      packages:
        - libopencv-dev
        - libopencv-imgproc-dev
        - libopencv-photo-dev
        - libboost-filesystem-dev
        - libboost-serialization-dev
        - libboost-locale-dev
        - libxml2-dev
        - libfreetype6-dev
        - libpng-dev
        - libjpeg-dev
        - libtiff-dev
        - libopenexr-dev
        - libpython3-dev
        - ruby-dev
        - swig
        - libqt5core5a
        - libqt5gui5
        - libqt5widgets5

before_script:
  - mkdir build
  - cd build
  - cmake .. -DWITH_QT=1 -DWITH_YAF_RUBY_BINDINGS=1

script:
  - make
